blockchain:
  ethereum:
    client:
      web-socket:
        url: wss://bsc-testnet.publicnode.com
    migrator:
      block-interval-size: 50
datasource:
  ethereum:
    url: jdbc:postgresql://localhost:5801/ethereum
    username: eth-user
    password: eth-password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 20
      minimum-idle: 1
      pool-name: ethereum-db-pool
    hibernate:
      order-inserts: true
      jdbc-batch-size: 100
      show-sql: false
