client:
  blockchain:
    web-socket:
      bnb-sc:
        url: wss://bsc-testnet.publicnode.com
datasource:
  bnb-sc:
    url: jdbc:postgresql://localhost:5800/bnb-sc
    username: bnb-sc-user
    password: bnb-sc-password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 20
      minimum-idle: 1
      pool-name: bnb-sc-db-pool