version: '3.9'

services:
  bnb-sc-database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: bnb-sc-user
      POSTGRES_PASSWORD: bnb-sc-password
      POSTGRES_DB: bnb-sc
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U bnb-sc-user" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5800:5432"